{{- if .Values.sockShop.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  labels:
    name: catalogue-db
  namespace: {{ include "sock-shop-litmus.sockShopNamespace" . }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: catalogue-db
{{- end }}
