{{- if .Values.sockShop.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    name: user
  namespace: {{ include "sock-shop-litmus.sockShopNamespace" . }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: user
{{- end }}
